#!/bin/bash

echo Inicio

#creamos el build

ionic build android --release



#FIRMAR APK
echo FIRMAR EL APK

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /Users/koala/Documents/keystore/ntskoala ./platforms/android/build/outputs/apk/android-release-unsigned.apk ntskoala

#ALINEAR Y RENOMBRAR

#IR AL DIR

cd ./platforms/android/build/outputs/apk/

zipalign -v 4 android-release-unsigned.apk ntskoala_rc2.apk

echo FIN DEL PROCESO